# Generated by Django 6.0 on 2026-01-01 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('canonical', 'Canonical'), ('user', 'User'), ('ai_generated', 'AI Generated')], default='user', max_length=20)),
                ('serving_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serving_unit', models.CharField(max_length=50)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('carb', 'Carb'), ('protein', 'Protein'), ('fat', 'Fat'), ('mixed', 'Mixed'), ('beverage', 'Beverage')], max_length=20, null=True)),
                ('glycemic_index', models.IntegerField(blank=True, null=True)),
                ('absorption_speed', models.CharField(blank=True, choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast')], max_length=20, null=True)),
                ('insulin_response', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('satiety_score', models.IntegerField(blank=True, null=True)),
                ('protein_quality', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High')], null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('post_workout', 'Post Workout'), ('beverage', 'Beverage')], max_length=20)),
                ('date', models.DateField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_assisted', 'AI Assisted')], default='manual', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealFoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='food.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('post_workout', 'Post Workout'), ('beverage', 'Beverage')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealTemplateFoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.fooditem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='food.mealtemplate')),
            ],
        ),
    ]
