# Generated by Django 6.0 on 2025-12-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('serving_size', models.FloatField()),
                ('serving_unit', models.CharField(max_length=50)),
                ('calories_per_serving', models.FloatField()),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('sugar_g', models.FloatField(default=0)),
                ('sodium_mg', models.FloatField(default=0)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_custom', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'food_items',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='MealFoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servings', models.FloatField(default=1)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'meal_food_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meal_templates',
            },
        ),
        migrations.CreateModel(
            name='MealTemplateFoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servings', models.FloatField(default=1)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'meal_template_food_items',
                'ordering': ['order'],
            },
        ),
    ]
