# Generated by Django 6.0 on 2025-12-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealfooditem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mealtemplatefooditem',
            options={},
        ),
        migrations.AlterModelTable(
            name='fooditem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='meal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mealfooditem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mealtemplate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mealtemplatefooditem',
            table=None,
        ),
    ]
