# Generated by Django 6.0 on 2025-12-30 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutpreset',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workoutpreset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanPreset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_presets', to='workouts.workoutplan')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_presets', to='workouts.workoutpreset')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan', 'preset')},
            },
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='presets',
            field=models.ManyToManyField(blank=True, related_name='plans', through='workouts.WorkoutPlanPreset', to='workouts.workoutpreset'),
        ),
    ]
