# Generated by Django 6.0 on 2025-12-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutpreset_is_public_alter_workoutpreset_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutpreset',
            name='day_label',
            field=models.CharField(blank=True, help_text="Day of week label like 'Monday', 'Tuesday'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workoutpreset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutpreset',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of tags like ['strength', 'cardio']"),
        ),
    ]
