# Generated by Django 6.0 on 2025-12-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutpreset_day_label_workoutpreset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
