# Generated by Django 6.0 on 2026-01-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workoutsession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='bodyweight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="User's bodyweight at the time of completing the exercise (for bodyweight exercises)", max_digits=6, null=True),
        ),
    ]
