# Generated by Django 6.0 on 2026-01-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workoutset_bodyweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='dropdown_weights',
            field=models.JSONField(blank=True, help_text='For dropdown sets, stores array of {weight, reps} for each drop set', null=True),
        ),
    ]
