# Generated by Django 6.0 on 2026-01-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workoutset_dropdown_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='bodyweight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="User's bodyweight at the time of the workout", max_digits=6, null=True),
        ),
    ]
