# Generated by Django 6.0 on 2026-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_workoutsession_bodyweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='set_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('bodyweight', 'Bodyweight'), ('dropdown', 'Dropdown'), ('warmup', 'Warmup')], default='normal', max_length=20),
        ),
    ]
