# Generated by Django 6.0 on 2026-08-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_workoutset_set_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation'), ('cardio', 'Cardio')], default='isolation', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
