from pydantic import BaseModel, Field
from typing import List, Optional, Literal
from datetime import datetime


class WorkoutSet(BaseModel):
    id: str
    exerciseId: str
    setType: Literal["normal", "warmup", "bodyweight"]
    weight: Optional[float] = None
    reps: int
    loggedAt: Optional[datetime] = None


class WorkoutSessionBase(BaseModel):
    name: str
    startedAt: datetime
    endedAt: Optional[datetime] = None
    sets: List[WorkoutSet] = []


class WorkoutSessionCreate(WorkoutSessionBase):
    pass


class WorkoutSession(WorkoutSessionBase):
    id: str
    totalVolume: float = 0

    model_config = {"from_attributes": True}


class WorkoutSessionUpdate(BaseModel):
    name: Optional[str] = None
    startedAt: Optional[datetime] = None
    endedAt: Optional[datetime] = None
    sets: Optional[List[WorkoutSet]] = None


class WorkoutPresetExercise(BaseModel):
    id: Optional[str] = None  # Optional for create, generated by server
    exerciseId: Optional[str] = None  # For superset groups
    type: Literal["normal", "warmup", "bodyweight", "dropdown", "superset"]
    sets: int = 3
    weight: Optional[float] = None
    reps: Optional[int] = None
    dropdowns: Optional[int] = None
    exercises: Optional[List["WorkoutPresetExercise"]] = None  # For superset


class WorkoutPreset(BaseModel):
    id: Optional[str] = None  # Optional for create, generated by server
    name: str
    exercises: List[WorkoutPresetExercise]
    status: Optional[str] = "active"
    tags: Optional[List[str]] = []
    dayLabel: Optional[str] = None  # Day of week label

    model_config = {"from_attributes": True}
