from pydantic import BaseModel, Field
from typing import List, Optional, Literal, Union
from datetime import datetime


class WorkoutSet(BaseModel):
    id: str
    exerciseId: str
    setType: Literal["normal", "warmup", "bodyweight"]
    weight: Optional[float] = None
    reps: int
    loggedAt: Optional[datetime] = None


class WorkoutSessionBase(BaseModel):
    name: str
    startedAt: datetime
    endedAt: Optional[datetime] = None
    sets: List[WorkoutSet] = []


class WorkoutSessionCreate(WorkoutSessionBase):
    pass


class WorkoutSession(WorkoutSessionBase):
    id: str
    totalVolume: float = 0

    model_config = {"from_attributes": True}


class WorkoutSessionUpdate(BaseModel):
    name: Optional[str] = None
    startedAt: Optional[datetime] = None
    endedAt: Optional[datetime] = None
    sets: Optional[List[WorkoutSet]] = None


class WorkoutPresetExercise(BaseModel):
    id: Optional[str] = None  # Optional for create, generated by server
    exerciseId: Optional[str] = None  # For superset groups
    type: Literal["normal", "warmup", "bodyweight", "dropdown", "superset"]
    sets: int = 3
    weight: Optional[float] = None
    reps: Optional[int] = None
    dropdowns: Optional[int] = None
    exercises: Optional[List["WorkoutPresetExercise"]] = None  # For superset
    warmup: Optional[bool] = False  # Whether to add warmup sets


class WorkoutPreset(BaseModel):
    id: Optional[str] = None  # Optional for create, generated by server
    name: str
    exercises: List[WorkoutPresetExercise]
    status: Optional[str] = "active"
    tags: Optional[List[str]] = []
    dayLabel: Optional[str] = None  # Day of week label

    model_config = {"from_attributes": True}


# Active workout state persistence
class ActiveWorkoutState(BaseModel):
    """State for an active workout being tracked"""
    preset: WorkoutPreset
    setRows: List[dict] = Field(default_factory=list, description="Serialized set items")
    startTime: datetime
    workoutSessionId: Optional[str] = None
    lastUsed: dict = Field(default_factory=dict, description="Last used weight/reps per exercise")

    model_config = {"from_attributes": True}


class ActiveWorkoutUpdate(BaseModel):
    """Update active workout state"""
    preset: Optional[WorkoutPreset] = None
    setRows: Optional[List[dict]] = None
    startTime: Optional[datetime] = None
    workoutSessionId: Optional[str] = None
    lastUsed: Optional[dict] = None


class CalculateVolumeRequest(BaseModel):
    """Request to calculate total volume from sets"""
    sets: List[WorkoutSet]


class CalculateVolumeResponse(BaseModel):
    """Response with calculated volume"""
    totalVolume: float
    completedSets: int
    totalSets: int


class BuildWorkoutFromPresetRequest(BaseModel):
    """Request to build set rows from a preset"""
    preset: WorkoutPreset
    exercises: List[dict] = Field(default_factory=list, description="Available exercises with id, name, bodyweight, equipment")


class SetRowItem(BaseModel):
    """A single set row item (can be normal, warmup, bodyweight, or dropdown)"""
    id: str
    exerciseId: str
    exerciseName: str
    setNumber: int
    setType: Literal["normal", "warmup", "bodyweight", "dropdown"]
    weight: Optional[float] = None
    reps: int
    completed: bool = False
    isBodyweight: bool = False
    suggestedWeight: Optional[float] = None
    isExtra: bool = False
    isSuperset: bool = False
    originalIndex: Optional[int] = None
    # For dropdown sets
    subSets: Optional[List[dict]] = None  # List of {weight, reps, completed, completedAt}

    model_config = {"from_attributes": True}


class BuildWorkoutResponse(BaseModel):
    """Response with built set rows"""
    setRows: List[SetRowItem]


class AnalyzeExerciseRequest(BaseModel):
    """Request to analyze an exercise from description or images"""
    description: str


class AnalyzeExerciseResponse(BaseModel):
    """Response with analyzed exercise data"""
    name: str
    category: Literal["compound", "isolation", "cardio"]
    muscleGroups: List[str]
    equipment: List[str]
    instructions: List[str]
    bodyweight: Optional[bool] = False
    confidence: float = Field(default=0.5, ge=0, le=1)
