AWSTemplateFormatVersion: '2010-09-09'
Description: Fitness Tracker Backend - AppSync, Cognito, DynamoDB, Lambda, S3

Parameters:
  OpenAIAPIKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key for AI features

Resources:
  # ============================================
  # Cognito User Pool
  # ============================================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: fitness-tracker-users
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireUppercase: true
          RequireSymbols: false
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: fitness-tracker-app
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: fitness-tracker-identity
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  # ============================================
  # IAM Roles
  # ============================================
  UnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: unauthenticated
      Policies:
        - PolicyName: UnauthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action: '*'
                Resource: '*'

  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: AuthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - appsync:GraphQL
                Resource: !Sub 'arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/*'
              - Effect: Allow
                Action:
                  - mobileanalytics:PutEvents
                Resource: '*'

  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt AuthenticatedRole.Arn
        unauthenticated: !GetAtt UnauthenticatedRole.Arn

  # ============================================
  # S3 Bucket for file storage
  # ============================================
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'fitness-tracker-storage-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  StorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StorageBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt StorageBucket.Arn
              - !Sub '${StorageBucket.Arn}/*'
            Condition:
              Bool:
                aws:SecureTransport: false

  # ============================================
  # DynamoDB Tables
  # ============================================
  # Using AppSync @model directive, tables will be auto-created
  # But we need IAM role for Lambda functions

  # ============================================
  # Lambda Execution Role
  # ============================================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/fitness-tracker-*'
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/fitness-tracker-*/index/*'
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !GetAtt StorageBucket.Arn
                  - !Sub '${StorageBucket.Arn}/*'

  # ============================================
  # Lambda Functions
  # ============================================
  ParseWorkoutFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: fitness-tracker-parse-workout
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIAPIKey
      Code:
        S3Bucket: !Sub 'fitness-tracker-lambda-code-${AWS::AccountId}'
        S3Key: lambda/parseWorkout/dist/index.js

  ParseFoodFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: fitness-tracker-parse-food
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIAPIKey
      Code:
        S3Bucket: !Sub 'fitness-tracker-lambda-code-${AWS::AccountId}'
        S3Key: lambda/parseFood/dist/index.js

  GenerateAdviceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: fitness-tracker-generate-advice
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIAPIKey
      Code:
        S3Bucket: !Sub 'fitness-tracker-lambda-code-${AWS::AccountId}'
        S3Key: lambda/generateAdvice/dist/index.js

  TranscribeVoiceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: fitness-tracker-transcribe-voice
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIAPIKey
      Code:
        S3Bucket: !Sub 'fitness-tracker-lambda-code-${AWS::AccountId}'
        S3Key: lambda/transcribeVoice/dist/index.js

  AnalyzeFoodPhotoFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: fitness-tracker-analyze-food-photo
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIAPIKey
      Code:
        S3Bucket: !Sub 'fitness-tracker-lambda-code-${AWS::AccountId}'
        S3Key: lambda/analyzeFoodPhoto/dist/index.js

  # ============================================
  # AppSync GraphQL API
  # ============================================
  GraphQLAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: fitness-tracker-api
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        UserPoolId: !Ref UserPool
        AwsRegion: !Ref AWS::Region
        DefaultAction: ALLOW

  # Additional IAM auth for public resources
  GraphQLAPIIAMConfig:
    Type: AWS::AppSync::GraphQLApi
    Condition: HasAdditionalAuthProviders
    Properties:
      Name: fitness-tracker-api-iam
      AuthenticationType: AWS_IAM

  # ============================================
  # GraphQL Schema
  # ============================================
  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      DefinitionS3Location: !Sub 's3://${StorageBucket}/schema.graphql'

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref IdentityPool
  GraphQLAPIUrl:
    Description: AppSync GraphQL API Endpoint
    Value: !GetAtt GraphQLAPI.GraphQLUrl
  GraphQLAPIId:
    Description: AppSync GraphQL API ID
    Value: !GetAtt GraphQLAPI.ApiId
  StorageBucketName:
    Description: S3 Bucket for file storage
    Value: !Ref StorageBucket
